/**
 * Represents a task entity for persistence and in-memory use.
 * @property id Optional unique identifier (generated by SQLite for new tasks)
 * @property description Description of the task
 * @property actionName Name of the action this task represents
 * @property payload Arbitrary payload data for the task
 * @property completed Whether the task is completed
 * @property retryCount Number of times this task has been retried
 * @property createdAt Date/time the task was created
 * @property updatedAt Date/time the task was last updated
 */
interface Task {
    id?: number;
    description: string;
    actionName: string;
    payload: any;
    completed: boolean;
    retryCount: number;
    createdAt: Date;
    updatedAt: Date;
}

export default Task;