interface Task{
    id?: string;  // Optional - will be generated by SQLite for new tasks
    description: string;
    actionName : string;
    payload : any;
    completed: boolean;
    retryCount: number;
    createdAt: Date;
    updatedAt: Date;
}

export default Task;